### PR TITLE
Try including rib-core

### PR DESCRIPTION
**Pull request by srid**

### CODE REVIEW

**Comment by srid** [comment]
It looks like you advanced rib after the package split done here: https://github.com/srid/rib/pull/165 - which makes rib two packages.

**Comment by JonathanReeve** [comment]
Thanks for this! I can't quite yet get my site to build with the latest Rib, for some reason. Will keep trying, though. It's possible I'm trying to update too many things at the same time, here.

**Comment by srid** [comment]
Looks like it is building here: https://github.com/JonathanReeve/jonreeve.com/runs/2598050421

**Comment by JonathanReeve** [comment]
Yep I got it to build by using an older version of Rib. I got it working with .org files, now! It just took a little bit of finessing.

**Pull request closed without merging**
